# Generated by Django 4.2 on 2023-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecution',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='execution_date',
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='execution_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
